language: node_js
node_js:
  - '6'
  - '5'
  - '4'
  - '0.12'
before_install:
  - 'npm install -g npm@latest'
notifications:
  email:
    on_success: change
    on_failure: always
after_success:
  - 'npm run coverage'
